### ISSUE TITLE
The stupid render line bug

### ISSUE THREAD

**Issue by NKY5223** [NKY5223/SkapClient#10]
There is a fix, don't use transforms and instead do it manually and using `Math.floor`

**Comment by ZeroTixDev** [comment]
console log the pos and tell me what it is (from the server of course)

**Comment by NKY5223** [comment]
> console log the pos and tell me what it is (from the server of course)

Uh wdym? Elaborate.

**Comment by ZeroTixDev** [comment]
you know how you are rendering the enemies at like obj.pos.x or whatever. console log those values and tell me what they are

**Comment by NKY5223** [comment]
are you sure
it will be very loggy

**Comment by ZeroTixDev** [comment]
i do not care, just tell me what kind of values you get ;p

**Comment by NKY5223** [comment]
okay
(make ur own branch >:3)

**Comment by ZeroTixDev** [comment]
bruh im telling you to do it, just tell me what kind of values you get, is it that hard??

**Comment by NKY5223** [comment]
yes i want to play skap i need ghost 3:P

**Comment by NKY5223** [comment]
fixed

**Comment by NKY5223** [comment]
> bruh im telling you to do it, just tell me what kind of values you get, is it that hard??

as of now you can just check map.objects etc
