### ISSUE TITLE
No arrow key movement

### ISSUE THREAD

**Issue by tritone246** [NKY5223/SkapClient#15]
add it now

**Comment by NKY5223** [comment]
no

**Comment by tritone246** [comment]
yes i already made the control div for that

**Comment by NKY5223** [comment]
okay but-
maybe l8er?

**Comment by tritone246** [comment]
no bc by then my pull request will be so many commits behind urs it will be very hard to add

**Comment by NKY5223** [comment]
hmm
i plan to addd the controls a bit differently so...

**Comment by tritone246** [comment]
just add it for now so i can actually play on ur client

**Comment by NKY5223** [comment]
>:C use WASD or just. okay. ill add a secret localStorage

**Comment by tritone246** [comment]
okokokokok

**Comment by NKY5223** [comment]
okay imma push, and then you can do 
`localStorage.setItem("keys", "arrowup arrowleft arrowdown arrowright shift qwerty qwerty r");`
(`qwerty` is just a placeholder for `""`)

**Comment by NKY5223** [comment]
okay pushed

**Comment by tritone246** [comment]
yay

**Comment by tritone246** [comment]
ok imma test it

**Comment by tritone246** [comment]
ok make freecam wasd if normal keys is arrow keys
