### ISSUE TITLE
Powers

### ISSUE THREAD

**Issue by tritone246** [NKY5223/SkapClient#16]
add powers

**Comment by NKY5223** [comment]
uh

**Comment by NKY5223** [comment]
well you gotta tell me how the power system works

**Comment by tritone246** [comment]
in
case "join" 
for the ws, add
powers = msg.i.powers;

**Comment by NKY5223** [comment]
ah yes

**Comment by NKY5223** [comment]
hmm

**Comment by NKY5223** [comment]
well guess what

**Comment by NKY5223** [comment]
this issue is about to close (in like 3 weeks)

**Comment by NKY5223** [comment]
o yea
for got to close
