### ISSUE TITLE
New Update, Everything Broke

### ISSUE THREAD

**Issue by rayhanadev** [NKY5223/SkapClient#29]
Welp it was a fun run. Now the client is broken :C.

**Comment by NKY5223** [comment]
lmao zero fixed it

**Comment by rayhanadev** [comment]
What do you mean :>? The site seems to be down now.

**Comment by ZeroTixDev** [comment]
I showed NKY the solution lol, I "think" he's adding it however he said he is removing the page for some reason e https://cdn.discordapp.com/attachments/662286342268649472/837482959250391040/unknown.png

**Comment by rayhanadev** [comment]
HAHAHHAHA

NKY in all seriousness why do you never accept our prs?

**Comment by NKY5223** [comment]
well maybe its becuase i never push

**Comment by rayhanadev** [comment]
Lol thanks for the invite to the repo.

Also wait what does pushing have to do with reviewing and merging prs?

**Comment by rayhanadev** [comment]
Since the client ~~is fixed~~ works pretty well I will close this issue :)
