### ISSUE TITLE
Client not working.

### ISSUE THREAD

**Issue by juli-beee** [NKY5223/SkapClient#37]
So I try to play on the skap client, and it gives me a disconnected message. Maybe it's because I'm on a school computer, but other people using school computers do not have this issue. Please help me!

**Comment by NKY5223** [comment]
perhaps its your school has disabled websockets for that computer. can you please screenshot the console when disconnected shows up?

**Comment by juli-beee** [comment]
Here is a picture
![image](https://user-images.githubusercontent.com/91574558/135263792-aa7f5c18-9195-49c7-9fe5-92895cf7721b.png)

**Comment by juli-beee** [comment]
it was working before.. maybe the servers are down?? i don't rlly know

**Comment by juli-beee** [comment]
wdym by console
also how to check if websockets enabled?

**Comment by juli-beee** [comment]
uhm hi so i was reading the changelog before skap crashed and and I did /bot and pressed + key and nothing happened.. but idk I don think that's why it crashed. it was working bad for my friend before I did the /bot  command

**Comment by juli-beee** [comment]
if it WAS my fault im really sorry about it

**Comment by NKY5223** [comment]
im sorry but i am unable to help you
