### ISSUE TITLE
How do I use the hacks

### ISSUE THREAD

**Issue by WeeWee161** [NKY5223/SkapClient#38]
I've been trying to use the hacks. My friends said to type in the search bar javascript:(Whatever the code is). It doesn't seem to work. Do I have to do something else?

**Comment by Elemental2468** [comment]
lol, the hacks aren't a thing on skap.io anymore because of a removal.

**Comment by NKY5223** [comment]
what hacks? also, be careful when using `javascript:`. it executes any javascript code, so your friend could steal your skap passwords

**Comment by Elemental2468** [comment]
"bots"

**Comment by NKY5223** [comment]
skapclient doesn't have hacks :P
