### ISSUE TITLE
the game severly lags

### ISSUE THREAD

**Issue by ZeroTixDev** [NKY5223/SkapClient#4]

**Comment by NKY5223** [comment]
it doesnt happen to me

**Comment by ZeroTixDev** [comment]
you are doing set interval with the requestanimation frame, thats totally wrong

**Comment by tritone246** [comment]
fake issue, it dont lag for me at all

**Comment by NKY5223** [comment]
okay zero do you wanna close this

**Comment by ZeroTixDev** [comment]
no, optimize it

**Comment by tritone246** [comment]
fake issue

**Comment by NKY5223** [comment]
OKay since this is basically fixed imma clser
